<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Detalhes da Avalicao <?php echo $this->id; ?>            
        </div>
    </div>
    <div class="panel-body">
        <dl class="dl-horizontal">
            <dt>Codigo:</dt>
            <dd><?php echo $this->form["codigo"]; ?></dd>
            <dt>Tipo de Avaliacao:</dt>
            <dd><?php echo $this->form["tipo de avaliacao"]; ?></dd>
        </dl>
    </div>
    <div class="panel-footer">
        <a href="<?php echo $this->url('avaliacao', array('action' => 'editar', 'id' => $this->id)); ?>" class="btn btn-warning btn-sm">Editar Avaliacao</a>
        <a href="<?php echo $this->url('avaliacao'); ?>" class="btn btn-default btn-sm">Voltar</a>
    </div>
</div>